### ISSUE TITLE
original source location

### ISSUE THREAD

**Issue by tropicalpb** [iychoi/HDF5HadoopReader#1]
Can I ask where is the original source?  I ran into two issues with this code:

1. if the hdf5 file has a custom vendor info at the beginning, the Read0(..) returned addresses need to shift by the number of blocks of 512 bytes taken up by the vendor info.  This is pretty simple to fix.
2. DataNode signature check fails, this is much more difficult to debug where addresses went awry.

thanks

**Comment by iychoi** [comment]
Hi,

It seems the URL to the source code has changed. I do not remember what code I used. But I remember that there was no pure Java implementation of HDF5 reader. So I referred to a C implementation (NetCDF) and reverse engineered HDF5 binary data files.
You may find similar code parts from below.
https://github.com/Unidata/thredds/tree/5.0.0/cdm/src/main/java/ucar/nc2/iosp/hdf5

I have no plan to update this source code. But if you are willing to use and update this code, please feel free to do so.

I found there is another project that implements HDF5 writer. You may get some hints from it.
https://github.com/NCAR/nujan

**Comment by tropicalpb** [comment]
I was able to find another project called jhdf.  With some hacks I am able to deal wit the Matlab v7.3 HDF5 based files now.  Thanks
